name: Corkwin CI

on: workflow_dispatch

jobs:
  build:
    name: Build Corkwin executable
    runs-on: ubuntu-latest
    steps:
      - name: Install Mingw-w64
        run: sudo apt-get install gcc-mingw-w64
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile
        run: x86_64-w64-mingw32-gcc -o corkwin.exe corkwin.c -lws2_32
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: corkwin
          path: corkwin.exe
